site_name: 'Alec on Cyber'
site_description: 'Cyber Security Information · Tools and Techniques'
site_author: 'Alec on Cyber'

repo_url: https://github.com/aleconcyber/aleconcyber.github.io

theme:
    name: null
    custom_dir: mkdocs_windmill_dark
    # default from mkdocs_theme.yml
    static_templates:
        - 404.html
    include_search_page: true
    search_index_only: true
    history_buttons: true
    article_nav_top: true
    article_nav_bottom: true

nav:
    - Home: index.md
    - Tools:
        - Windows: 
            - PowerShell: sample-a.md
        - Logging:
            - Splunk: splunk.md
            - Sample Subpage A2: sample-a2.md
        - Cloud: 
            - Docker: sample-b.md
            - AWS: sample-a.md

markdown_extensions:
    - toc:
        permalink: '#'

extra:
    version: 0.1.1
